CREATE TABLE Clientes (
    IDCliente INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    IDFormulario VARCHAR(255) NOT NULL,
    Nombre VARCHAR(255) NOT NULL,
    Apellido VARCHAR(255) NOT NULL,
    Telefono1 VARCHAR(20) NOT NULL,
    Telefono2 VARCHAR(20),
    Telefono3 VARCHAR(20),
    Telefono4 VARCHAR(20),
    Telefono5 VARCHAR(20),
    Correo1 VARCHAR(255),
    Correo2 VARCHAR(255),
    Correo3 VARCHAR(255),
    Oportunidad1 VARCHAR(255),
    Oportunidad2 VARCHAR(255),
    Oportunidad3 VARCHAR(255),
    OportunidadFinal VARCHAR(255),
    OportunidadFinal_1 VARCHAR(255),
    OportunidadFinal_2 VARCHAR(255),
    Codigo_Linkedin VARCHAR(255),
    Area_Formacion VARCHAR(255),
    Cargo VARCHAR(255),
    Industria VARCHAR(255),
    Area_Trabajo VARCHAR(255),
    Empresa VARCHAR(255),
    Tipo_Cliente VARCHAR(255),
    Pais VARCHAR(255),
    FechadeCreacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
